GET http://127.0.1.1:3000/helloworld HTTP/1.1
content-type: application/json

###

GET http://127.0.1.1:3000/recipes HTTP/1.1
content-type: application/json

###

POST http://127.0.1.1:3000/recipes HTTP/1.1
Content-Type: application/json

{
    "name":"Käsekuchen",
    "description":"Leckerer hausgemachter Käsekuchen mit wenig Fett",
    "minutes_needed":"120"
}

###

DELETE http://127.0.1.1:3000/recipes/3 HTTP/1.1
Content-Type: application/json

###

PUT http://127.0.1.1:3000/recipes/2 HTTP/1.1
Content-Type: application/json

{
    "name":"Käsekuchen",
    "description":"Leckerer hausgemachter Käsekuchen mit wenig Fett",
    "minutes_needed":"125"
}